version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - apt-get install python3-pip -y
      - pip install --upgrade pip
  pre_build:
    commands:
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'
